#!/usr/bin/env python3
# -*- coding:utf-8 -*-
"""Sprint-Layout的PCB导出为kicad PCB文件
比Gerber要好, 能保留大部分可编辑信息, 但是不完美, 因为没有网表
Author: cdhigh <https://github.com/cdhigh>
"""
import datetime, math, os, uuid
from .kicad_definitions import *
from sprint_struct.sprint_textio import *
from .netlist_builder import NetlistBuilder
from .kicad_footprint_lib import assignLibraryFootprints
from .sprint_to_kicad_mod import KicadModGenerator

def uuid4():
    return str(uuid.uuid4())

#保留小数位数的同时,能处理一些None或非法值之类的,比如{var:.2f}健壮
def r2(value):
    try:
        return round(value, 2)
    except:
        return 0

class KicadGenerator:
    #textIo: SprintTextIO对象
    #libFolder: 生成封装库(.pretty目录)的路径, 为空则不生成封装库
    def __init__(self, textIo, libFolder=None):
        self.textIo = textIo
        self.libFolder = libFolder
        self._componentNo = 0
        builder = NetlistBuilder(textIo)
        self.netlist = builder.build()
        #相同封装的元件共用库中的同一个footprint
        self.libNames = {}
        self.libRepComps = {}
        if libFolder:
            comps = [e for e in textIo.children() if isinstance(e, SprintComponent)]
            if comps:
                self.libNames, self.libRepComps = assignLibraryFootprints(comps)

    def compNo(self):
        self._componentNo += 1
        return self._componentNo
    
    #导出到KICAD的主接口, 失败返回错误信息
    def generate(self, outputFile):
        try:
            with open(outputFile, 'w', encoding='utf-8') as f:
                self.writeHeader(f)
                self.writeLayers(f)
                self.writeSetup(f)
                self.writeNetlist(f)
                self.writeElements(f)
                self.writeFooter(f)
            return self.writeLibrary()
        except Exception as e:
            return str(e)

    #将库中每种footprint存为一个.kicad_mod文件, 失败返回错误信息
    def writeLibrary(self):
        if not self.libFolder or not self.libRepComps:
            return ''
        try:
            os.makedirs(self.libFolder, exist_ok=True)
        except Exception as e:
            return str(e)
        for name, comp in self.libRepComps.items():
            err = KicadModGenerator(comp, name, forLibrary=True).generate(
                os.path.join(self.libFolder, name + '.kicad_mod'))
            if err:
                return f"{name}: {err}"
        return ''

    #Get KiCad layer name from Sprint layer index
    def getLayerName(self, layerIdx):
        return sprintLayerMap.get(layerIdx, "Dwgs.User")

    #SOLDERMASK=true elements get an opening copy on the mask layer
    #front side (C1/S1/I1) -> F.Mask, back side (C2/S2/I2) -> B.Mask, rest -> None
    def maskLayerFor(self, layerIdx):
        if layerIdx in (LAYER_C1, LAYER_S1, LAYER_I1):
            return 'F.Mask'
        if layerIdx in (LAYER_C2, LAYER_S2, LAYER_I2):
            return 'B.Mask'
        return None

    def writeHeader(self, f):
        dateStr = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        f.write('(kicad_pcb\n')
        f.write('  (version 20241229)\n')
        f.write('  (generator "sprint_converter")\n')
        f.write('  (generator_version "9.0")\n')
        f.write('  (general\n')
        f.write('    (thickness 1.6)\n')
        f.write('    (legacy_teardrops no)\n')
        f.write('  )\n')
        f.write('  (paper "A4")\n')
        f.write('  (title_block\n')
        f.write('    (title "Converted from Sprint-Layout v6.0")\n')
        f.write(f'    (date "{dateStr}")\n')
        f.write('    (comment 1 "Generated by sprintFont")\n')
        f.write('  )\n')

    def writeLayers(self, f):
        f.write('  (layers\n')
        f.write('    (0 "F.Cu" signal)\n')
        f.write('    (1 "In1.Cu" signal)\n')
        f.write('    (2 "In2.Cu" signal)\n')
        f.write('    (31 "B.Cu" signal)\n')
        f.write('    (32 "B.Adhes" user "B.Adhesive")\n')
        f.write('    (33 "F.Adhes" user "F.Adhesive")\n')
        f.write('    (34 "B.Paste" user)\n')
        f.write('    (35 "F.Paste" user)\n')
        f.write('    (36 "B.SilkS" user "B.Silkscreen")\n')
        f.write('    (37 "F.SilkS" user "F.Silkscreen")\n')
        f.write('    (38 "B.Mask" user)\n')
        f.write('    (39 "F.Mask" user)\n')
        f.write('    (40 "Dwgs.User" user "User.Drawings")\n')
        f.write('    (41 "Cmts.User" user "User.Comments")\n')
        f.write('    (42 "Eco1.User" user "User.Eco1")\n')
        f.write('    (43 "Eco2.User" user "User.Eco2")\n')
        f.write('    (44 "Edge.Cuts" user)\n')
        f.write('    (45 "Margin" user)\n')
        f.write('    (46 "B.CrtYd" user "B.Courtyard")\n')
        f.write('    (47 "F.CrtYd" user "F.Courtyard")\n')
        f.write('    (48 "B.Fab" user)\n')
        f.write('    (49 "F.Fab" user)\n')
        f.write('  )\n')

    def writeSetup(self, f):
        f.write('  (setup\n')
        f.write('    (pad_to_mask_clearance 0)\n')
        f.write('    (allow_soldermask_bridges_in_footprints no)\n')
        f.write('    (tenting front back)\n')
        f.write('    (pcbplotparams\n')
        f.write('      (layerselection 0x00010fc_ffffffff)\n')
        f.write('      (plot_on_all_layers_selection 0x0000000_00000000)\n')
        f.write('      (disableapertmacros no)\n')
        f.write('      (usegerberextensions no)\n')
        f.write('      (usegerberattributes yes)\n')
        f.write('      (usegerberadvancedattributes yes)\n')
        f.write('      (creategerberjobfile yes)\n')
        f.write('      (dashed_line_dash_ratio 12.000000)\n')
        f.write('      (dashed_line_gap_ratio 3.000000)\n')
        f.write('      (svgprecision 4)\n')
        f.write('      (plotframeref no)\n')
        f.write('      (mode 1)\n')
        f.write('      (useauxorigin no)\n')
        f.write('      (hpglpennumber 1)\n')
        f.write('      (hpglpenspeed 20)\n')
        f.write('      (hpglpendiameter 15.000000)\n')
        f.write('      (pdf_front_fp_property_popups yes)\n')
        f.write('      (pdf_back_fp_property_popups yes)\n')
        f.write('      (pdf_metadata yes)\n')
        f.write('      (pdf_single_document no)\n')
        f.write('      (dxfpolygonmode yes)\n')
        f.write('      (dxfimperialunits yes)\n')
        f.write('      (dxfusepcbnewfont yes)\n')
        f.write('      (psnegative no)\n')
        f.write('      (psa4output no)\n')
        f.write('      (plot_black_and_white yes)\n')
        f.write('      (sketchpadsonfab no)\n')
        f.write('      (plotpadnumbers no)\n')
        f.write('      (hidednponfab no)\n')
        f.write('      (sketchdnponfab yes)\n')
        f.write('      (crossoutdnponfab yes)\n')
        f.write('      (subtractmaskfromsilk no)\n')
        f.write('      (outputformat 1)\n')
        f.write('      (mirror no)\n')
        f.write('      (drillshape 1)\n')
        f.write('      (scaleselection 1)\n')
        f.write('      (outputdirectory "")\n')
        f.write('    )\n')
        f.write('  )\n')

    def writeNetlist(self, f):
        f.write('  (net 0 "")\n')
        for net in self.netlist['nets']:
            f.write(f'  (net {net["number"]} "{net["name"]}")\n')
        f.write('  (embedded_fonts no)\n')

    def writeElements(self, f):
        self._processGroup(f, self.textIo)

    def _processGroup(self, f, group, centroid=(0,0), isFree=True, _padNo=None):
        #_padNo为共享计数器, 保证分组内焊盘和库文件中的焊盘序号一致
        if _padNo is None:
            _padNo = [0]
        for elem in group.elements:
            if isinstance(elem, SprintTrack):
                self._writeTrack(f, elem, centroid)
            elif isinstance(elem, SprintPad):
                _padNo[0] += 1
                #Free thru-hole pad (not grouped, not in component) becomes a via
                if centroid == (0,0) and isFree and elem.padType == 'PAD' and elem.drill:
                    self._writeVia(f, elem)
                else:
                    self._writePad(f, elem, centroid, _padNo[0])
            elif isinstance(elem, SprintPolygon):
                self._writeZone(f, elem, centroid)
            elif isinstance(elem, SprintText):
                self._writeText(f, elem, centroid)
            elif isinstance(elem, SprintCircle):
                self._writeCircle(f, elem, centroid)
            elif isinstance(elem, SprintGroup):
                self._processGroup(f, elem, centroid, isFree=False, _padNo=_padNo)
            elif isinstance(elem, SprintComponent):
                self._writeComponent(f, elem)

    #写导线,kicad的每个转折点都要一个单独的segment,靠网表和首尾坐标相互连接,kicad快捷键为U
    #格式: (segment (start x y) (end x y) (width w) (layer Name) (net 0) (uuid UUID))
    #或 (fp_line (start x y) (end x y) (stroke (width w) (type solid)) (layer Name) (uuid UUID))
    #或 (gr_line (start x y) (end x y) (stroke (width w) (type solid)) (layer Name) (uuid UUID))
    #注意: 网络只有数字标识没有名字, uuid名字也可以是tstamp
    #f: 文件句柄
    #track: SprintTrack实例
    #centroid: 所属元件(footprint)的几何中心, =(0,0)为孤立元素
    def _writeTrack(self, f, track, centroid=(0,0)):
        points = track.points
        if len(points) < 2:
            return

        space = '  ' if centroid == (0,0) else '    '

        layer = self.getLayerName(track.layerIdx)
        #SOLDERMASK=true: copper artwork stays, plus an opening copy on mask
        maskLayer = self.maskLayerFor(track.layerIdx) if getattr(track, 'soldermask', None) else None
        maskName = 'fp_line' if centroid != (0,0) else 'gr_line'
        if centroid != (0,0): #封装内不管是导线还是绘图线都使用fp_line
            name = 'fp_line'
            width = f'(stroke (width {r2(track.width)}) (type solid))'
            net = ''
        elif track.layerIdx in (LAYER_S1, LAYER_S2, LAYER_U): #kicad导线和绘图线是分开的
            name = 'gr_line'
            width = f'(stroke (width {r2(track.width)}) (type solid))'
            net = ''
        else:
            name = 'segment'
            width = f'(width {r2(track.width)})'
            netNum = self.netlist['element_net_map'].get(id(track), 0)
            net = f'(net {netNum}) '

        for i in range(len(points) - 1):
            p1 = points[i]
            p2 = points[i + 1]
            x1, y1 = r2(p1[0] - centroid[0]), r2(p1[1] - centroid[1])
            x2, y2 = r2(p2[0] - centroid[0]), r2(p2[1] - centroid[1])
            f.write(f'{space}({name} (start {x1} {y1}) (end {x2} {y2}) '
                   f'{width} (layer {layer}) {net}(uuid {uuid4()}))\n')
            if maskLayer:
                f.write(f'{space}({maskName} (start {x1} {y1}) (end {x2} {y2}) '
                       f'{width} (layer {maskLayer}) (uuid {uuid4()}))\n')

    #Free thru-hole pad exported as via (not grouped, not in component)
    #Format: (via (at x y) (size d) (drill d) (layers "F.Cu" "B.Cu") (net n) (uuid UUID))
    #f: file handle
    #pad: SprintPad instance (padType PAD with drill)
    def _writeVia(self, f, pad):
        x, y = r2(pad.pos[0]), r2(pad.pos[1])
        sizeX, sizeY = pad.sizeX, pad.sizeY
        if pad.form in (PAD_FORM_RECT_H, PAD_FORM_RECT_ROUND_H, PAD_FORM_RECT_OCTAGON_H):
            sizeX *= 2
        elif pad.form in (PAD_FORM_RECT_V, PAD_FORM_RECT_ROUND_V, PAD_FORM_RECT_OCTAGON_V):
            sizeY *= 2
        viaSize = max(max(sizeX, sizeY), 0.1)
        drill = pad.drill or 0
        if drill <= 0 or drill >= viaSize:
            viaSize = max(viaSize, drill + 0.2)
        viaSize, drill = r2(viaSize), r2(drill)
        netNum = self.netlist['element_net_map'].get(id(pad), 0)
        f.write(f'  (via (at {x} {y}) (size {viaSize}) (drill {drill}) '
               f'(layers "F.Cu" "B.Cu") (net {netNum}) (uuid {uuid4()}))\n')

    #转换焊盘,kicad不允许孤立焊盘存在,必须依附于某个footprint,
    #如果没有外层footprint, 这里需要创建一个footprint包裹焊盘
    #centroid: 所属元件(footprint)的几何中心, =(0,0)为孤立元素
    #padNo: 在元件内的焊盘序号, 从1开始
    def _writePad(self, f, pad, centroid=(0,0), padNo=1):
        layer = self.getLayerName(pad.layerIdx)
        rotation = sprintAngleToKicad(pad.rotation)
        sizeX = r2(max(pad.sizeX, 0.1))
        sizeY = r2(max(pad.sizeY, 0.1))
        x, y = r2(pad.pos[0] - centroid[0]), r2(pad.pos[1] - centroid[1])

        # 通孔焊盘
        if pad.padType == 'PAD':
            padType = "thru_hole"
            if pad.via:
                padLayers = "*.Cu *.Mask"
            elif pad.layerIdx == LAYER_C1:
                padLayers = "F.Cu F.Mask"
            else:
                padLayers = "B.Cu B.Mask"
            drillDef = f'(drill {r2(pad.drill)})'
            if pad.form == PAD_FORM_SQUARE:
                shape = "rect"
            elif pad.form == PAD_FORM_RECT_H:
                shape = "rect"
                sizeX = r2(sizeX * 2)
            elif pad.form == PAD_FORM_RECT_V:
                shape = "rect"
                sizeY = r2(sizeY * 2)
            elif pad.form in (PAD_FORM_RECT_ROUND_H, PAD_FORM_RECT_OCTAGON_H):
                shape = "oval"
                sizeX = r2(sizeX * 2)
            elif pad.form in (PAD_FORM_RECT_ROUND_V, PAD_FORM_RECT_OCTAGON_V):
                shape = "oval"
                sizeY = r2(sizeY * 2)
            else:
                shape = "circle"
        else: #贴片焊盘
            padType = "smd"
            if layer.endswith(".Cu"):
                padLayers = f'{layer} {layer.replace(".Cu", ".Mask")} {layer.replace(".Cu", ".Paste")}'
            else:
                padLayers = layer
            drillDef = ""
            shape = "rect"
        
        if centroid == (0,0): #创建一个footprint包括孤立焊盘
            compNo = self.compNo()
            fpId = f"Pad_{int(x * 100)}_{int(y * 100)}_{compNo}"
            f.write(f'  (footprint "{fpId}" (layer "{layer}")\n')
            f.write(f'    (at {x} {y} 0) (uuid {uuid4()})\n')
            f.write(f'    (property "Reference" "CMP{compNo}" (at 0 0 0) (layer "{layer}") (hide yes) (uuid {uuid4()}) (effects (font (size 1 1) (thickness 0.15))))\n')
            f.write(f'    (property "Value" "" (at 0 0 0) (layer "{layer.replace(".Cu", ".Fab")}") (hide yes) (uuid {uuid4()}) (effects (font (size 1 1) (thickness 0.15))))\n')
            f.write(f'    (property "Footprint" "" (at 0 0 0) (unlocked yes) (layer "{layer.replace(".Cu", ".Fab")}") (hide yes) (uuid {uuid4()}) (effects (font (size 1 1) (thickness 0.15))))\n')
            f.write('    (attr smd)\n' if padType == "smd" else '    (attr through_hole)\n')
            #rotation写在外层会导致旋转失效
            netNum = self.netlist['element_net_map'].get(id(pad), 0)
            netName = f"Net-{netNum}" if netNum > 0 else ""
            f.write(f'    (pad "1" {padType} {shape} (at 0 0 {rotation}) (size {sizeX} {sizeY}) '
                   f'{drillDef} (layers {padLayers}) (net {netNum} "{netName}") (uuid {uuid4()}))\n')
            f.write(f'  )\n')
        else:
            netNum = self.netlist['element_net_map'].get(id(pad), 0)
            netName = f"Net-{netNum}" if netNum > 0 else ""
            f.write(f'    (pad "{padNo}" {padType} {shape} (at {x} {y} {rotation}) (size {sizeX} {sizeY}) '
                   f'{drillDef} (layers {padLayers}) (net {netNum} "{netName}") (uuid {uuid4()}))\n')

    #转换多边形区域
    #格式: (zone (net 0) (net_name "") (layer LayerName) (uuid UUID) (hatch edge 0.5)...)
    #或 (fp_poly (pts (xy X Y)...) (layer LayerName) (stroke (width w) (type solid)) (fill yes) (uuid UUID))
    #centroid: 所属元件(footprint)的几何中心, =(0,0)为孤立元素
    def _writeZone(self, f, zone, centroid=(0,0)):
        layer = self.getLayerName(zone.layerIdx)
        if centroid == (0,0):
            self._writeBoardZone(f, zone, layer)
        else:
            #封装内的禁止铺铜区不能在铜层创建多边形, 否则会短路
            rawIsCopper = layer.endswith('.Cu')
            if zone.cutout and rawIsCopper:
                layer = "Cmts.User"
            pts = [(r2(p[0] - centroid[0]), r2(p[1] - centroid[1])) for p in zone.points]
            f.write('    (fp_poly\n')
            f.write('      (pts\n')
            for x, y in pts:
                f.write(f'        (xy {x} {y})\n')
            f.write('      )\n')
            f.write(f'      (layer {layer}) (stroke (width {zone.width}) (type solid)) (fill yes) (uuid {uuid4()})\n')
            f.write('    )\n')
            #SOLDERMASK=true: 另在阻焊层加同样的开口拷贝
            hasMaskFlag = getattr(zone, 'soldermask', None) or getattr(zone, 'soldermaskCutout', None)
            if hasMaskFlag and not (zone.cutout and rawIsCopper):
                maskLayer = self.maskLayerFor(zone.layerIdx)
                if maskLayer:
                    self._writeMaskPoly(f, pts, maskLayer, zone.width, 'fp_poly', '    ')

    #电路板层的多边形, 只有铜层才能转换为原生zone, 其他板层转换为图形对象
    #Sprint不允许铺铜区带空洞, 用户用CUTOUT多边形压在铺铜上来挖空,
    #这里转换为原生的keepout zone, KiCad填充时自动打出空洞
    def _writeBoardZone(self, f, zone, layer):
        pts = [(r2(p[0]), r2(p[1])) for p in zone.points]
        if len(pts) < 3:
            return #退化轮廓, KiCad无法加载
        isCopper = layer.endswith('.Cu')
        hasMaskFlag = getattr(zone, 'soldermask', None) or getattr(zone, 'soldermaskCutout', None)
        if isCopper:
            self._writeCopperZone(f, zone, layer, pts, isKeepout=bool(zone.cutout))
            #SOLDERMASK=true: 铜图形保留, 另在阻焊层加同样的开口拷贝
            if hasMaskFlag and not zone.cutout:
                maskLayer = self.maskLayerFor(zone.layerIdx)
                if maskLayer:
                    self._writeMaskPoly(f, pts, maskLayer, zone.width, 'gr_poly', '  ')
        elif zone.cutout:
            #非铜层的禁区转换为通用keepout规则区, 任何板层都合法
            self._writeCopperZone(f, zone, layer, pts, isKeepout=True)
        elif layer == 'Edge.Cuts':
            #板框外形转换为闭合gr_line环
            for i in range(len(pts)):
                p1, p2 = pts[i], pts[(i + 1) % len(pts)]
                f.write(f'  (gr_line (start {p1[0]} {p1[1]}) (end {p2[0]} {p2[1]}) '
                       f'(layer Edge.Cuts) (stroke (width {r2(zone.width)}) (type solid)) (uuid {uuid4()}))\n')
        else:
            #丝印等 artwork 转换为图形多边形
            f.write('  (gr_poly\n')
            f.write('    (pts\n')
            for x, y in pts:
                f.write(f'      (xy {x} {y})\n')
            f.write('    )\n')
            f.write(f'    (layer {layer}) (stroke (width {r2(zone.width)}) (type solid)) (fill yes) (uuid {uuid4()})\n')
            f.write('  )\n')

    #SOLDERMASK=true的开口拷贝, 同样的多边形画到阻焊层
    #name: 'gr_poly'或'fp_poly'
    def _writeMaskPoly(self, f, pts, maskLayer, width, name, space):
        f.write(f'{space}({name}\n')
        f.write(f'{space}  (pts\n')
        for x, y in pts:
            f.write(f'{space}    (xy {x} {y})\n')
        f.write(f'{space}  )\n')
        f.write(f'{space}  (layer {maskLayer}) (stroke (width {r2(width)}) (type solid)) (fill yes) (uuid {uuid4()})\n')
        f.write(f'{space})\n')

    #原生铜区或keepout区, keepout压在铜区上形成与Sprint CUTOUT等效的空洞
    def _writeCopperZone(self, f, zone, layer, pts, isKeepout):
        netNum = 0 if isKeepout else self.netlist['element_net_map'].get(id(zone), 0)
        netName = "" if isKeepout else (f"Net-{netNum}" if netNum > 0 else "")
        f.write(f'  (zone (net {netNum}) (net_name "{netName}") (layer {layer}) (uuid {uuid4()}) (hatch edge 0.5)\n')
        f.write(f'    (connect_pads (clearance {zone.clearance}))\n')
        if isKeepout: #禁止铺铜区
            f.write('    (min_thickness 0.1) (filled_areas_thickness no)\n')
            f.write('    (keepout (tracks allowed) (vias allowed) (pads allowed)'
                    ' (copperpour not_allowed) (footprints allowed))\n')
        else:
            f.write('    (min_thickness 0.254) (filled_areas_thickness no)\n')
        f.write('    (fill yes (thermal_gap 0.5) (thermal_bridge_width 0.5))\n')
        f.write('    (polygon\n')
        f.write('      (pts\n')
        for x, y in pts:
            f.write(f'        (xy {x} {y})\n')
        f.write('      )\n')
        f.write('    )\n')
        f.write('  )\n')

    #转换文本
    #格式: (gr_text "content" (at x y angle) (layer LayerName) (effects ...) (uuid UUID) ...)
    #或:  (fp_text TYPE "content" (at x y angle) (layer LayerName) (hide yes) (effects ...) (uuid UUID))
    #centroid: 所属元件(footprint)的几何中心, =(0,0)为孤立元素
    def _writeText(self, f, text, centroid=(0,0)):
        layer = self.getLayerName(text.layerIdx)
        content = text.text.replace('"', '\\"')
        rotation = sprintAngleToKicad(text.rotation)

        # 镜像的处理比较麻烦, 垂直镜像等价于水平镜像+旋转180
        isMirrored = text.mirrorH
        if text.mirrorV:
            isMirrored = not isMirrored
            rotation = (rotation + 180) % 360

        # KiCad 只有 "justify mirror" (沿X轴水平镜像)
        justify = " (justify mirror)" if isMirrored else ""

        height = r2(text.height)
        x, y = r2(text.pos[0] - centroid[0]), r2(text.pos[1] - centroid[1])
        if centroid == (0,0):
            name = 'gr_text'
            space = '  '
        else:
            name = 'fp_text user'
            space = '    '
        
        f.write(f'{space}({name} "{content}" (at {x} {y} {rotation}) (layer {layer}) (uuid {uuid4()})\n')
        f.write(f'{space}  (effects (font (size {height} {height})){justify})\n')
        f.write(f'{space})\n')
        #SOLDERMASK=true: opening copy on mask layer
        maskLayer = self.maskLayerFor(text.layerIdx) if getattr(text, 'soldermask', None) else None
        if maskLayer:
            f.write(f'{space}({name} "{content}" (at {x} {y} {rotation}) (layer {maskLayer}) (uuid {uuid4()})\n')
            f.write(f'{space}  (effects (font (size {height} {height})){justify})\n')
            f.write(f'{space})\n')

    #转换圆弧
    #格式: (gr_circle (center x y) (end x y) (stroke ...) (layer LayerName) (fill no)...)
    #或: (fp_circle (center x y) (end x y) (stroke ...) (layer LayerName) (fill no)...)
    #或: (gr_arc (start X Y) (mid X Y) (end X Y) (stroke ...) (layer LayerName) (width w)...)
    #或: (fp_arc (start X Y) (mid X Y) (end X Y) (stroke ...) (layer LayerName) (width w)...)
    #centroid: 所属元件(footprint)的几何中心, =(0,0)为孤立元素
    def _writeCircle(self, f, circle, centroid=(0,0)):
        layer = self.getLayerName(circle.layerIdx)
        space = '  ' if centroid == (0,0) else '    '
        self._writeCircleOnLayer(f, circle, centroid, layer, space)
        #SOLDERMASK=true: opening copy on mask layer
        maskLayer = self.maskLayerFor(circle.layerIdx) if getattr(circle, 'soldermask', None) else None
        if maskLayer:
            self._writeCircleOnLayer(f, circle, centroid, maskLayer, space)

    #圆/圆弧绘制到指定板层
    #f: 文件句柄
    #circle: SprintCircle实例
    #centroid: 所属元件(footprint)的几何中心, =(0,0)为孤立元素
    #layer/space: 目标板层名和缩进
    def _writeCircleOnLayer(self, f, circle, centroid, layer, space):
        start = r2(circle.start)
        stop = r2(circle.stop)
        cx, cy = r2(circle.center[0] - centroid[0]), r2(circle.center[1] - centroid[1])
        fill = 'yes' if circle.fill else 'no'

        # 正圆
        if start == stop:
            endX = r2(cx + circle.radius)
            endY = cy
            name = 'gr_circle' if centroid == (0,0) else 'fp_circle'
            f.write(f'{space}({name} (center {cx} {cy}) (end {endX} {endY}) '
                   f'(stroke (width {r2(circle.width)}) (type solid)) (fill {fill}) '
                  f'(layer {layer}) (uuid {uuid4()}))\n')
        elif circle.fill:
            #填充圆弧(比如填充半圆): 圆弧无法表示填充半盘, 导出为每10度一个点的多边形
            self._writeArcPolygon(f, circle, centroid, layer, space)
        else: # 圆弧
            name = 'gr_arc' if centroid == (0,0) else 'fp_arc'
            start, mid, end = circle.calcStartEndMidPoint()
            start = r2(start[0] - centroid[0]), r2(start[1] - centroid[1])
            mid = r2(mid[0] - centroid[0]), r2(mid[1] - centroid[1])
            end = r2(end[0] - centroid[0]), r2(end[1] - centroid[1])
            f.write(f'{space}({name} (start {start[0]} {start[1]}) (mid {mid[0]} {mid[1]}) (end {end[0]} {end[1]}) '
                   f'(stroke (width {r2(circle.width)}) (type solid)) (fill {fill}) '
                  f'(layer {layer}) (uuid {uuid4()}))\n')

    #填充圆弧导出为多边形, 沿圆弧每10度取一个点, 多边形自动闭合形成填充半盘
    #格式: (gr_poly (pts (xy X Y)...) (layer LayerName) (stroke ...) (fill yes) (uuid UUID))
    #或: (fp_poly (pts (xy X Y)...) (layer LayerName) (stroke ...) (fill yes) (uuid UUID))
    #f: 文件句柄
    #circle: SprintCircle实例(填充圆弧, start != stop)
    #centroid: 所属元件(footprint)的几何中心, =(0,0)为孤立元素
    #layer/space: 板层名和缩进, 和调用方保持一致
    def _writeArcPolygon(self, f, circle, centroid, layer, space):
        sweep = (circle.stop - circle.start) % 360
        if sweep == 0:
            sweep = 360
        steps = max(int(math.ceil(sweep / 10.0)), 1)
        cx0, cy0 = circle.center
        pts = []
        for i in range(steps + 1):
            angle = math.radians(circle.start + sweep * i / steps)
            x = r2(cx0 + circle.radius * math.cos(angle) - centroid[0])
            y = r2(cy0 - circle.radius * math.sin(angle) - centroid[1])
            pts.append((x, y))
        name = 'gr_poly' if centroid == (0,0) else 'fp_poly'
        f.write(f'{space}({name}\n')
        f.write(f'{space}  (pts\n')
        for x, y in pts:
            f.write(f'{space}    (xy {x} {y})\n')
        f.write(f'{space}  )\n')
        f.write(f'{space}  (layer {layer}) (stroke (width {r2(circle.width)}) (type solid)) (fill yes) (uuid {uuid4()})\n')
        f.write(f'{space})\n')

    #元件, 生成一个footprint
    #f: file对象
    #comp: SprintComponent实例
    def _writeComponent(self, f, comp):
        centroid = comp.centroid()
        layer = self.getLayerName(comp.layerIdx)
        compNo = self.compNo()
        #相同封装的元件使用库中同一个footprint名
        libName = self.libNames.get(id(comp))
        fpId = libName if libName else f"FP_{int(centroid[0] * 100)}_{int(centroid[1] * 100)}_{compNo}"
        f.write(f'  (footprint "{fpId}" (layer "{layer}")\n')
        f.write(f'    (at {r2(centroid[0])} {r2(centroid[1])} 0) (uuid {uuid4()})\n')

        #元件名字
        namePos = comp.idText.pos
        if not namePos or namePos == (0,0):
            nameX = nameY = 0
        else:
            nameX, nameY = r2(namePos[0] - centroid[0]), r2(namePos[1] - centroid[1])
        nRotation = sprintAngleToKicad(comp.idText.rotation)
        nLayer = self.getLayerName(comp.idText.layerIdx)
        hide = 'no' if comp.idText.visible and comp.idText.text else 'yes'
        height = r2(comp.idText.height)
        name = comp.idText.text if comp.idText.text else f'CMP{compNo}'
        f.write(f'    (property "Reference" "{name}" (at {nameX} {nameY} {nRotation})'
            f' (layer "{nLayer}") (hide {hide}) (uuid {uuid4()}) (effects (font (size {height} {height}) (thickness 0.15))))\n')

        #元件值
        valuePos = comp.valueText.pos
        if not valuePos or valuePos == (0,0):
            valueX = valueY = 0
        else:
            valueX, valueY = r2(valuePos[0] - centroid[0]), r2(valuePos[1] - centroid[1])
        vRotation = sprintAngleToKicad(comp.valueText.rotation)
        vLayer = self.getLayerName(comp.valueText.layerIdx)
        hide = 'no' if comp.valueText.visible and comp.valueText.text else 'yes'
        f.write(f'    (property "Value" "{comp.valueText.text}" (at {valueX} {valueY} {vRotation}) (layer "{vLayer}")'
            f' (hide {hide}) (uuid {uuid4()}) (effects (font (size {height} {height}) (thickness 0.15))))\n')

        #Footprint (封装源)：表示是从哪个库里的哪个封装来的。比如:Package_SO:SOIC-8_3.9x4.9mm_P1.27mm
        footprintLink = libName if libName else ""
        f.write(f'    (property "Footprint" "{footprintLink}" (at 0 0 0) (unlocked yes) (layer "{layer.replace(".Cu", ".Fab")}") (hide yes) (uuid {uuid4()}) (effects (font (size 1 1) (thickness 0.15))))\n')
        f.write(f'    (attr {comp.getMountingType()})\n')

        #转换下层元素
        self._processGroup(f, comp, centroid, isFree=False)
        f.write(f'  )\n')

    def writeFooter(self, f):
        f.write(')\n')
